export const SWITCH_TO_CHAT = "SWITCH_TO_CHAT";
export const SWITCH_TO_HOME = "SWITCH_TO_HOME";
export const SHOW_CUSTOMER_MODAL = "SHOW_CUSTOMER_MODAL";
export const HIDE_CUSTOMER_MODAL = "HIDE_CUSTOMER_MODAL";
export const ONSUBMIT_CUSTOMER_DATA = "ONSUBMIT_CUSTOMER_DATA";
export const ADD_NEW_CUSTOMER = "ADD_NEW_CUSTOMER";
export const ADD_NEW_CUSTOMER_SUCCESS = "ADD_NEW_CUSTOMER_SUCCESS";
export const ADD_NEW_CUSTOMER_ERROR = "ADD_NEW_CUSTOMER_ERROR";
export const HIDE_ADD_NEW_CUSTOMER_ERROR = "HIDE_ADD_NEW_CUSTOMER_ERROR";
export const GET_ALL_CUSTOMERS = "GET_ALL_CUSTOMERS";
export const GET_HUBBA_CUSTOMERS = "GET_HUBBA_CUSTOMERS";
export const GET_HUBSPOT_CUSTOMERS = "GET_HUBSPOT_CUSTOMERS";
export const GET_HUBSPOT_CUSTOMERS_ERROR = "GET_HUBSPOT_CUSTOMERS_ERROR";
export const GET_ALL_CUSTOMERS_SUCCESS = "GET_ALL_CUSTOMERS_SUCCESS";
export const GET_ALL_CUSTOMERS_ERROR = "GET_ALL_CUSTOMERS_ERROR";
export const GET_MESSAGES_FOR_CUSTOMER = "GET_MESSAGES_FOR_CUSTOMER";
export const GET_MESSAGES_FOR_CUSTOMER_SUCCESS =
  "GET_MESSAGES_FOR_CUSTOMER_SUCCESS";
export const GET_MESSAGES_FOR_CUSTOMER_FAILED =
  "GET_MESSAGES_FOR_CUSTOMER_FAILED";
export const GET_SUBSCRIBED_TO_MESSAGES = "GET_SUBSCRIBED_TO_MESSAGES";
export const SET_ACTIVE_CUSTOMER = "SET_ACTIVE_CUSTOMER";
export const GET_CUSTOMER_DEALS = "GET_CUSTOMER_DEALS";
export const GET_CUSTOMER_DEALS_SUCCESS = "GET_CUSTOMER_DEALS_SUCCESS";
export const GET_CUSTOMER_DEALS_ERROR = "GET_CUSTOMER_DEALS_ERROR";
export const GET_ALL_OWNERS = "GET_ALL_OWNERS";
export const GET_ALL_OWNERS_ERROR = "GET_ALL_OWNERS_ERROR";
export const GET_ALL_OWNERS_SUCCESS = "GET_ALL_OWNERS_SUCCESS";
